stages: 
  filter_kirthi_panoids: 
    cmd: python src/filter_panoids.py
    deps: 
      - src/filter_panoids.py
    outs:
      - outputs/filtered_panoids.csv
  get_oxgraph:
    cmd: python src/get_oxgraph.py inputs/Detroit_Boxes.geojson outputs/oxgraph.csv
    deps: 
      - src/get_oxgraph.py
      - inputs/Detroit_Boxes.geojson
    outs: 
      - outputs/oxgraph.csv
  get_queryable_points: 
    cmd: python src/get_queryable_points.py outputs/oxgraph.csv outputs/queryable_points.csv
    deps: 
      - src/get_queryable_points.py
      - outputs/oxgraph.csv
    outs: 
      - outputs/queryable_points.csv
  filter_queryable_points:
    cmd: python src/filter_queryable_points.py inputs/Troy_MadisonHeights.geojson outputs/queryable_points.csv outputs/filtered_queryable_points.csv
    deps: 
      - src/filter_queryable_points.py
      - outputs/queryable_points.csv
    outs: 
      - outputs/filtered_queryable_points.csv
  get_flats: 
    cmd: python src/get_panoramas.py outputs/filtered_queryable_points.csv outputs/panoramas
    deps:
      - src/get_panoramas.py
      - outputs/filtered_queryable_points.csv